# Generated by Django 5.0.1 on 2024-01-25 14:58

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('fathers_name', models.CharField(max_length=50)),
                ('mothers_name', models.CharField(max_length=50)),
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'", regex='^\\d{10}$')])),
                ('Class', models.IntegerField()),
                ('section', models.CharField(max_length=50)),
                ('Roll', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100)),
                ('student_image', models.ImageField(upload_to='studentProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
